# Часть 1

In [1]:
import numpy as np


__1.__ Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;<br>
   Так как количество столбцов матрицы A не равно количеству строк матрицы B, то операция не возможна.<br>
   __Ответ: произведение не определено.__

   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;<br>
   Произведение определено, т.к. количество столбцов матрицы A равно количеству строк матрицы B.<br>
   Размерность результирующей матрицы: $2\times3$<br>
   __Ответ: произведение определено; размерность $2\times3$__

   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;<br>
   Произведение определено, т.к. количество столбцов матрицы A равно количеству строк матрицы B.<br>
   Размерность результирующей матрицы: $8\times8$<br>
   __Ответ: произведение определено; размерность $8\times8$__

   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.<br>
   роизведение определено, т.к. количество столбцов матрицы A равно количеству строк матрицы B.<br>
   Размерность результирующей матрицы: $4\times4$<br>
   __Ответ: произведение определено; размерность $4\times4$__

__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A+B=\begin{pmatrix}
1+4&-2-1\\
3+0&0+5
\end{pmatrix}=\begin{pmatrix}
5&-3\\
3&5
\end{pmatrix}$<br><br>
$A\times B=\begin{pmatrix}
1*4+(-2)*0 & 1*(-1)+(-2)*5\\
3*4+0*0 & 3*(-1)+0*(5)
\end{pmatrix}=\begin{pmatrix}
4&-11\\
12&-3
\end{pmatrix}$


In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
np.add(A, B)

array([[ 5, -3],
       [ 3,  5]])

In [3]:
np.dot(A, B)

array([[  4, -11],
       [ 12,  -3]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A = 3\begin{pmatrix}
1&7\\
3&-6
\end{pmatrix}=\begin{pmatrix}
3&21\\
9&-18
\end{pmatrix}$<br><br>
$2B=2\begin{pmatrix}
0&5\\
2&-1
\end{pmatrix}=\begin{pmatrix}
0&10\\
4&-2
\end{pmatrix}$<br><br>
$4C=4\begin{pmatrix}
2&-4\\
1&1
\end{pmatrix}=\begin{pmatrix}
8&-16\\
4&4
\end{pmatrix}$

$3A-2B=\begin{pmatrix}
3&11\\
5&-16
\end{pmatrix}$

$3A-2B+4C=\begin{pmatrix}
11&-5\\
9&-12
\end{pmatrix}$

In [4]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

In [5]:
3*A-2*B+4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

$A^{T}=\begin{pmatrix}
4&5&2\\
1&-2&3
\end{pmatrix}$

$AA^{T}=\begin{pmatrix}
4*4+1*1&4*5+1*(-2)&4*2+1*3\\
5*4-2*1&5*5-2*(-2)&5*2-2*3\\
2*4+3*1&2*5+3*(-2)&2*2+3*3
\end{pmatrix}=\begin{pmatrix}
17&18&11\\
18&29&4\\
11&4&13
\end{pmatrix}
$

$A^{T}A=\begin{pmatrix}
4*4+5*5+2*2&4*1+5*(-2)+2*3\\
1*4-2*5+3*2&1*1-2*(-2)+3*3
\end{pmatrix}=\begin{pmatrix}
45&0\\
0&14
\end{pmatrix}$

In [6]:
A=np.array([[4, 1], [5, -2], [2, 3]])
At = A.transpose()
At

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [7]:
np.dot(A, At)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [8]:
np.dot(At, A)

array([[45,  0],
       [ 0, 14]])

__5*.__ Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [9]:
def product(A, B):
    if len(A[0]) != len(B):
        return 'Number of columns of first matrix is not equal to number of rows of second matrix'
    result = [[0 for j in range(len(B[0]))] for i in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(A[0])):
                result[i][j] += A[i][k]*B[k][j]
    return result

In [10]:
product(A, B)

[[2, 19], [-4, 27], [6, 7]]

In [11]:
np.dot(A, B)

array([[ 2, 19],
       [-4, 27],
       [ 6,  7]])

# Часть 2


__1.__ Вычислите определитель:

a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}=
sinx*sinx+cosx*cosx=1$<br>

__Ответ: 1__

б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}
=4\begin{vmatrix}
5&1\\
0&9
\end{vmatrix}-
0\begin{vmatrix}
2&3\\
0&9
\end{vmatrix}+
0\begin{vmatrix}
2&3\\
5&1
\end{vmatrix}=4*(5*9-0*1)=4*45=180$<br>

__Ответ: 180__

In [13]:
A = np.array([[4, 2, 3],
              [0, 5, 1],
              [0, 0, 9]])
np.linalg.det(A)

180.0

в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=
1\begin{vmatrix}
5&6\\
8&9
\end{vmatrix}-
2\begin{vmatrix}
4&6\\
7&9
\end{vmatrix}+
3\begin{vmatrix}
4&5\\
7&8
\end{vmatrix}=1*(5*9-6*8)-2*(4*9-6*7)+3*(4*8-5*7)=$<br>$=45-48-2*(36-42)+3*(32-35)=-3+12+-9=0$<br>
__Ответ: 0__

In [29]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
round(np.linalg.det(A), 10)

-0.0

__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) $det(A^{2}) = det(A*A) = det(A)*det(A) = 16$<br>
__Ответ: 16__

б) $det(A^{T})=det(A)=4$<br>
__Ответ: 4__

в) Т.к. при умножении строки/столбца матрицы на число определитель умножается на это же число, то при умножении матрицы на число мы умножаем каждую строку на число и определитель произведения матрицы на число равен произведению определителя на число в степени количества строк или столбцов.<br>
$det(2A) = 2^{n}*4$, где n - количество строк/столбцов матрицы<br>
__Ответ: $4*2^n$__

__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

1-я строка и 2-я строка линейно зависимы: если умножим 1-ю строку на -2 получим 2-ю строку. Поэтому по свойству определителей определитель равен 0.<br>
Т.к. определитель равен 0, то эта матрица вырожденная по определению.<br>

In [30]:
A = np.array([[-2, 7, -3],
              [4, -14, 6],
              [-3, 7, 13]])
np.linalg.det(A)

0.0

__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

3-я строка является суммой 1-й и 2-й строки, поэтому её можно отбросить:<br>
$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
\end{pmatrix}$
<br>Из 2-й строки отнимем 1-ю, получим:<br>
$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2\\ 
\end{pmatrix}$<br>
Таким образом ранг матрицы равен 2<br>
__Ответ: 2__

In [34]:
A = np.array([[1, 2, 3],
              [1, 1, 1],
              [2, 3, 4]])
np.linalg.matrix_rank(A)

2

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Т.к. 3-я строка явл-ся линейной комбинацией 1-й и 2-й строк, можем её убрать
$$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$$
Отнимем из 1-й строки 2-ю, получим:
$$\begin{pmatrix}
0 & 0 & 0 & -1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$$
Т.о. ранг матрицы равен 3<br>
__Ответ: 3__

In [33]:
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(A)

3