# Часть 1

__1.__ Решите систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

$\begin{pmatrix}
\left.\begin{matrix}
1&1&-1&-2\\
2&1&-1&1\\
1&1&-3&1
\end{matrix}
\right|\begin{matrix}
0\\-2\\4
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1&1&-1&-2\\
0&-1&1&5\\
0&0&-2&3
\end{matrix}
\right|\begin{matrix}
0\\-2\\4
\end{matrix}
\end{pmatrix}
$

Система имеет бесконечное кол-во решений. Пусть $x_4=C$ - свободный параметр, тогда:

$$\begin{cases}
x_3=(4-3C)/(-2)=\frac{3}{2}C-2,\\
x_2=(-2-5C-\frac{3}{2}C+2)/(-1)=\frac{13}{2}C,\\
x_1=2C+\frac{3}{2}C-2-\frac{13}{2}C=-3C-2.
\end{cases}
$$
Получили общее решение системы.
__Ответ: $\begin{pmatrix}-3C-2\\ \frac{13}{2}C\\ \frac{3}{2}C-2 \\C\end{pmatrix}$, где C - произвольная константа.__

__2.__ Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$  

Запишем расширенную матрицу:
$$A=\begin{pmatrix}
\left.\begin{matrix}
3&-1&1\\
2&-5&-3\\
1&1&-1
\end{matrix}\right|\begin{matrix}
4\\-17\\0\end{matrix}\end{pmatrix}$$
Столбцы матрицы линейно независимы. Три линейно независимых вектора образуют в трехмерном пространстве базис и любой вектор можно выразить через линейную комбинацию базисных векторов единственным образом.

Таким образом, система совместна и имеет единственное решение.

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
3&-1&1\\
2&-5&-3\\
1&1&-1
\end{matrix}\right|\begin{matrix}
4\\-17\\0\end{matrix}\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1&1&-1\\
0&-4&4\\
0&-7&-1
\end{matrix}\right|\begin{matrix}
0\\4\\-17\end{matrix}\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1&1&-1\\
0&-1&1\\
0&-7&-1
\end{matrix}\right|\begin{matrix}
0\\1\\-17\end{matrix}\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1&1&-1\\
0&1&-1\\
0&-7&-1
\end{matrix}\right|\begin{matrix}
0\\-1\\-17\end{matrix}\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1&1&-1\\
0&1&-1\\
0&0&-8
\end{matrix}\right|\begin{matrix}
0\\-1\\-24\end{matrix}\end{pmatrix}
$$

$rankA=rank\tilde{A}=n=3$<br>Тогда по теореме Кронекера-Капелли такая система совместна и определена, т.е. имеет единственное решение.<br>
__Ответ: система совместна и имеет единственное решение.__ 

In [1]:
import numpy as np

In [2]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
A_tilde = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])

print(f'Ранг основной матрицы = {np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы = {np.linalg.matrix_rank(A_tilde)}')

Ранг основной матрицы = 3
Ранг расширенной матрицы = 3


б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

Запишем расширенную матрицу:
$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
2&-4&6\\
1&-2&3\\
3&-6&9
\end{matrix}\right|
\begin{matrix}
1\\-2\\5\end{matrix}
\end{pmatrix}$$

Все столбцы исходной матрицы линейно зависимы, т.е. все три вектора лежат на одной прямой, другим словами принадлежат некоторому одномерному линейному подпространству исходного трехмерного пространства.

Вектор правой части и столбцы исходной матрицы линейно независимы. Это значит, что вектор правой части не принадлежит линейному подпространству, то есть не лежит на этой прямой.

Таким образом, система несовместна.

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
2&-4&6\\
1&-2&3\\
3&-6&9
\end{matrix}\right|
\begin{matrix}
1\\-2\\5\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1&-2&3\\
2&-4&6\\
3&-6&9
\end{matrix}\right|
\begin{matrix}
-2\\1\\5\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1&-2&3\\
0&0&0\\
0&0&0
\end{matrix}\right|
\begin{matrix}
-2\\5\\11\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1&-2&3\\
0&0&0
\end{matrix}\right|
\begin{matrix}
-2\\5\end{matrix}
\end{pmatrix}$$

$$rankA=1<rank\tilde{A}=2.$$
Т.к. ранг основной матрицы меньше ранга расширенной матрицы, то по теореме Кронекера-Капелли такая система несовместна.<br>
__Ответ: система несовместна.__

In [3]:
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
A_tilde = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])

print(f'Ранг основной матрицы = {np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы = {np.linalg.matrix_rank(A_tilde)}')

Ранг основной матрицы = 1
Ранг расширенной матрицы = 2


в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

Запишем расширенную матрицу:
$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1&2&5\\
3&1&-8
\end{matrix}\right|
\begin{matrix}
4\\-2
\end{matrix}\end{pmatrix}$$
Столбцы матрицы линейно независимы. Три линейно независимых вектора образуют в трехмерном пространстве базис и любой вектор можно выразить через линейную комбинацию базисных векторов единственным образом.

Таким образом, система совместна и имеет единственное решение.

Проверим с помощью теоремы Кронекера-Капелли. Путем элементарных преобразований приведем матрицу к ступенчатому виду.

$$\begin{pmatrix}
\left.\begin{matrix}
1&2&5\\
3&1&-8
\end{matrix}\right|
\begin{matrix}
4\\-2
\end{matrix}\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1&2&5\\
0&-5&-23
\end{matrix}\right|
\begin{matrix}
4\\-14
\end{matrix}\end{pmatrix}$$
Видно, что ранг основной матрицы $A$ совпадает с рангом расширенной матрицы $\tilde{A} 
$$rankA=rank\tilde{A}=2<n=3.$
Тогда по теореме Кронекера-Капелли такая система совместна и имеет бесконечное количество решений.

__Ответ: система совместна и имеет бесконечное количество решений.__

In [4]:
A = np.array([[1, 2, 5], [3, 1, -8]])
A_tilde = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])

print(f'Ранг основной матрицы = {np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы = {np.linalg.matrix_rank(A_tilde)}')

Ранг основной матрицы = 2
Ранг расширенной матрицы = 2


__3.__ Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

Ранг основной матрицы $A$ совпадает с рангом расширенной матрицы $\tilde{A}$ и равен числу неизвестных n.
$$rankA=rank\tilde{A}=n=4$$
Тогда по т. Кронекера-Капелли такая система совместима и определена.<br>
__Ответ: система совместна и имеет одно решение.__

In [5]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
A_tilde = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])

print(f'Ранг основной матрицы = {np.linalg.matrix_rank(A)}')
print(f'Ранг расширенной матрицы = {np.linalg.matrix_rank(A_tilde)}')

Ранг основной матрицы = 4
Ранг расширенной матрицы = 4


__4.__ Дана система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найдите соотношение между параметрами $a$, $b$ и $c$, при которых система считается несовместной.

Приведем матрицу к ступенчатому виду с помощью элементарных преобразований.

$$\begin{pmatrix}
\left.\begin{matrix}
1&2&3\\
0&-3&-6\\
0&-6&-12
\end{matrix}\right|
\begin{matrix}
a\\b-4a\\c-7a
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1&2&3\\
0&-3&-6\\
0&-6&-12
\end{matrix}\right|
\begin{matrix}
a\\b-4a\\c-7a
\end{matrix}
\end{pmatrix}=
\begin{pmatrix}
\left.\begin{matrix}
1&2&3\\
0&-3&-6\\
0&0&0
\end{matrix}\right|
\begin{matrix}
a\\b-4a\\a-2b+c
\end{matrix}
\end{pmatrix}
$$

Если $a-2b+c\neq0$, то $rankA=2<rank\tilde{A}=3$ и по т. Кронекера-Капелли система будет несовместной.

__Ответ: при $a-2b+c\neq0$ система будет несовместной.__

# Часть 2

__1.__ Решите систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

Вычислим определитель матрицы:
$$detA=
\begin{vmatrix}
1&-2\\
3&-4
\end{vmatrix}=
-4+6=2\neq0,$$
т.е. система совместна.

Вычислим определители $detA_1, detA_2,$ получаемые заменой $i$-го столбца на вектор правой части.
$$detA_1=
\begin{vmatrix}
1&-2\\
7&-4
\end{vmatrix}=
-4+14=10,$$
$$detA_2=
\begin{vmatrix}
1&1\\
3&7
\end{vmatrix}=
7-3=4.$$
Тогда по формуле Крамера получим решение:
$$x_1=\frac{detA_1}{detA}=10/2=5$$<br>
$$x_2=\frac{detA_2}{detA}=4/2=2$$<br>
__Ответ: $\begin{pmatrix}5\\2\end{pmatrix}.$__

In [6]:
A = np.array([[1, -2], [3, -4]])
b = np.array([1, 7])

x = np.linalg.solve(A, b)

print(f'Матрица A =\n{A}\n')
print(f'Вектор правой части b =\n{b}\n')
print(f'Решение x_numpy =\n{x}')

Матрица A =
[[ 1 -2]
 [ 3 -4]]

Вектор правой части b =
[1 7]

Решение x_numpy =
[5. 2.]


   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

Вычислим определитель матрицы:
$$detA=\begin{vmatrix}
2&-1&5\\
1&1&-3\\
2&4&1
\end{vmatrix}=2*(1+12)+(1+6)+5*(4-2)=2*13+7+5*2=26+7+10=43\neq0$$
т.е. система совместна.<br>
Вычислим определители $detA_1, detA_2, detA_3$ получаемые заменой $i$-го столбца на вектор правой части:

$$detA_1\begin{vmatrix}
10&-1&5\\
-2&1&-3\\
1&4&1
\end{vmatrix}=10*13+(-2+3)+5*(-8-1)=130+1-45=86$$

$$detA_2\begin{vmatrix}
2&10&5\\
1&-2&-3\\
2&1&1
\end{vmatrix}=2*(-2+3)-10*(1+6)+5*(1+4)=2-70+25=-43$$

$$detA=\begin{vmatrix}
2&-1&10\\
1&1&-2\\
2&4&1
\end{vmatrix}=2*(1+8)+(1+4)+10*(4-2)=18+5+20=43$$
Тогда по формуле Крамера получим решение:
$$x_1=\frac{detA_1}{detA}=86/43=2$$
$$x_2=\frac{detA_2}{detA}=-43/43=-1$$
$$x_3=\frac{detA_3}{detA}=43/43=1$$
__Ответ: $\begin{pmatrix}2\\-1\\1\end{pmatrix}$__

In [7]:
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1])

x = np.linalg.solve(A, b)

print(f'Матрица A =\n{A}\n')
print(f'Вектор правой части b =\n{b}\n')
print(f'Решение x_numpy =\n{x}')

Матрица A =
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]

Вектор правой части b =
[10 -2  1]

Решение x_numpy =
[ 2. -1.  1.]


__2*.__ Найдите $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

Выполним преобразования $(2)-2\cdot(1), (3)-3\cdot(1)$. Матрица примет вид:

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$$
Матрица L:
$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix}$$

Выполним преобразования $(3)-4\cdot(2)$. Получим искомые матрицы:

$$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$$
Матрица L:
$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$$

__Ответ: $\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$__

In [8]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
L = np.array([[1, 0, 0], [2, 1, 0], [3, 4, 1]])
U = np.array([[1, 2, 4], [0, 5, 4], [0, 0, 2]])

print(f'A =\n{A}\n')
print(f'LU =\n{np.dot(L, U)}')

A =
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]

LU =
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]


   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

Выполним преобразования $(2)-2\cdot(1), (3)-3\cdot(1), (4)-4\cdot(1)$. Матрица системы примет следующий вид:
$$\begin{pmatrix}
1 & 1 & 2 & 4\\
0 & 3 & 4 & 1\\
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}$$

А матрица L:
$$L=\begin{pmatrix}
1 & 0 & 0 & 0\\
2 & 1 & 0 & 0\\
3 & l_{32} & 1 & 0\\
4 & l_{42} & l_{43} & 1
\end{pmatrix}$$

Теперь выполним $(3)-5\cdot(2), (4)-6\cdot(2)$. Получим
$$\begin{pmatrix}
1 & 1 & 2 & 4\\
0 & 3 & 4 & 1\\
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}$$

Матрица L:
$$L=\begin{pmatrix}
1 & 0 & 0 & 0\\
2 & 1 & 0 & 0\\
3 & 5 & 1 & 0\\
4 & 6 & l_{43} & 1
\end{pmatrix}$$

Выполним $(4)-7\cdot(3)$ и получим:
$$\begin{pmatrix}
1 & 1 & 2 & 4\\
0 & 3 & 4 & 1\\
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$$

Матрица L:
$$L=\begin{pmatrix}
1 & 0 & 0 & 0\\
2 & 1 & 0 & 0\\
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$$

__Ответ: $L=\begin{pmatrix}
1 & 0 & 0 & 0\\
2 & 1 & 0 & 0\\
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$__

In [9]:
A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
L = np.array([[1, 0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 1]])
U = np.array([[1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3, 1], [0, 0, 0, 4]])

print(f'A =\n{A}\n')
print(f'LU =\n{np.dot(L, U)}')

A =
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]

LU =
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]


__3*.__ Решите систему линейных уравнений методом $LU$-разложения:

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

Матрица системы и вектор правой части имеют вид:
$$\begin{pmatrix}
2 & 1 & 3\\
11 & 7 & 5\\
9 & 8 & 4
\end{pmatrix}, b=
\begin{pmatrix}
1 \\ -6 \\ -5
\end{pmatrix}$$

Выполним преобразование $(2)-\frac{11}{2}\cdot(1), (3)-\frac{9}{2}\cdot(1)$, получим:
$$\begin{pmatrix}
2 & 1 & 3\\
0 & \frac{3}{2} & -\frac{23}{2}\\
0 & \frac{7}{2} & -\frac{19}{2}
\end{pmatrix}$$

$$L=\begin{pmatrix}
1 & 0 & 0\\
\frac{11}{2} & 1 & 0\\
\frac{9}{2} & l_{32} & 1
\end{pmatrix}$$

Выполним преобразование $(3)-\frac{7}{3}\cdot(2)$, получим:
$$\begin{pmatrix}
2 & 1 & 3\\
0 & \frac{3}{2} & -\frac{23}{2}\\
0 & 0 & \frac{104}{6}
\end{pmatrix}$$

$$L=\begin{pmatrix}
1 & 0 & 0\\
\frac{11}{2} & 1 & 0\\
\frac{9}{2} & \frac{7}{3} & 1
\end{pmatrix}$$

Теперь решим систему
$$Ly=b,$$

$$\begin{cases}
y_{1}=1,\\
\frac{11}{2}y_{1} + y_{2} = -6,\\
\frac{9}{2}y_{1} + \frac{7}{3}y_{2} + y_{3} = -5.
\end{cases}\Rightarrow
\begin{cases}
y_{1} = 1,\\
y_{2} = -6-\frac{11}{2}y_{1} = -6 - \frac{11}{2}=-\frac{23}{2},\\
y_{3} = -5-\frac{9}{2}y_{1}-\frac{7}{3}y_{2}=-5-\frac{9}{2}+\frac{161}{6}=\frac{161-27-30}{6}=\frac{104}{6}=\frac{52}{3}.
\end{cases}
$$

$$\begin{cases}
y_{1} = 1,\\
y_{2} = -\frac{23}{2},\\
y_{3} = \frac{52}{3}.
\end{cases}$$

Затем решим систему

$$Ux = y,$$

$$\begin{cases}
2x_1+x_2+3x_3=1,\\
\frac{3}{2}x_2-\frac{23}{2}x_3=-\frac{23}{2},\\
\frac{104}{6}x_3=\frac{52}{3}.
\end{cases}\Rightarrow
\begin{cases}
x_1=\frac{1}{2}(1-3x_3-x_2)=\frac{1}{2}(1-0-3)=-1,\\
x_2=\frac{2}{3}(-\frac{23}{2}+\frac{23}{2}x_3)=\frac{2}{3}(-\frac{23}{2}+\frac{23}{2})=0,\\
x_3=1.
\end{cases}$$

Получили решение
$$\begin{cases}
x_1 = -1\\
x_2 = 0\\
x_3 = 1
\end{cases}$$

__Ответ: $\begin{pmatrix}
-1 \\
0 \\
1 
\end{pmatrix}$__

In [10]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])

L = np.array([[1, 0, 0], [11 / 2, 1, 0], [9 / 2, 7 / 3, 1]])
U = np.array([[2, 1, 3], [0, 3 / 2, -23 / 2], [0, 0, 52 / 3]])

x = np.linalg.solve(A, b)

print(f'Матрица A =\n{A}\n')
print(f'Вектор правой части b =\n{b}\n')
print(f'LU =\n{np.dot(L, U)}\n')

print(f'Решение x_numpy =\n{x}')

Матрица A =
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]

Вектор правой части b =
[ 1 -6 -5]

LU =
[[ 2.  1.  3.]
 [11.  7.  5.]
 [ 9.  8.  4.]]

Решение x_numpy =
[-1.00000000e+00  2.44249065e-16  1.00000000e+00]


__4*.__ Решите систему линейных уравнений методом Холецкого:

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

Матрица системы и вектор правой части имеют вид:
$$A=\begin{pmatrix}
81 & - 45 & 45 \\
-45 & 50 & -15\\
45 & -15 & 38
\end{pmatrix}, b =
\begin{pmatrix}
531 \\ -460 \\ 193
\end{pmatrix}$$

Элементы матрицы $L$ рассчитываются по формулам:
$$l_{ii}=\sqrt{a_{ii}-\sum_{k = 1}^{i - 1}l_{ik}^{2}},$$

$$l_{ji}=\frac{1}{l_{ii}} \left( a_{ji} - \sum_{k = 1}^{j - 1}l_{ik}l_{jk} \right), \; j < i.$$

Выполним разложение $LL^{T}$:
$$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9,$$

$$l_{21}=\frac{a_{21}}{l_{11}} = \frac{-45}{9}=-5,$$

$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5,$$

$$l_{22}=\sqrt{a_22-l_{21}^2}=\sqrt{50-25}=5,$$

$$l_{32} = \frac{1}{l_{22}} (a_{32} - l_{31} l_{21}) = \frac{1}{5} (-15 + 25) = 2,$$

$$l_{33} = \sqrt{a_{33} - l_{31}^2 - l_{32}^2} = \sqrt{38 - 25 - 4} = 3.$$

Получили матрицу
$$L=\begin{pmatrix}
9 & 0 & 0 \\
-5 & 5 & 0 \\
5 & 2 & 3
\end{pmatrix}, L^{T}=
\begin{pmatrix}
9 & -5 & 5 \\
0 & 5 & 2 \\
0 & 0 & 3
\end{pmatrix}$$

Решим систему
$$Ly=b,$$

$$\begin{cases}
9y_1 = 531, \\
-5y_1 + 5y_2 = -460,\\
5y_1 + 2y_2 + 3y_3 = 193.
\end{cases}\Rightarrow
\begin{cases}
y_1 = 59, \\
y_2 = \frac{1}{5}(-460+5y_1)=-33\\
y_3 = \frac{1}{3}(193-2y_2-5y_1) = -12.
\end{cases}$$

$$\begin{cases}
y_1 = 59, \\
y_2 = -33,\\
y_3 = -12.
\end{cases}$$

Решим систему:
$$L^{T}x=y,$$

$$\begin{cases}
9x_1 - 5x_2 + 5x_3 = 59, \\
5x_2 + 2x_3 = -33,\\
3x_3 = -12.
\end{cases}\Rightarrow
\begin{cases}
x_3 = -4,\\
x_2 = (-33 -2x_3) / 5 = (-33+8)/5=-5,\\
x_1 = (59 - 5x_3 + 5x_2)/9 = (59 + 20 - 25) / 9 = 54/9=6
\end{cases}\Rightarrow
\begin{cases}
x_1 = 6,\\
x_2 = -5,\\
x_3 = -4
\end{cases}$$

__Ответ: $\begin{pmatrix}
6 \\ -5 \\ -4
\end{pmatrix}$.__

In [11]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

L = np.linalg.cholesky(A)

x = np.linalg.solve(A, b)

print(f'Матрица A =\n{A}\n')
print(f'Вектор правой части b =\n{b}\n')
print(f'L_numpy =\n{L}\n')

print(f'Решение x_numpy =\n{x}')

Матрица A =
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]

Вектор правой части b =
[ 531 -460  193]

L_numpy =
[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]

Решение x_numpy =
[ 6. -5. -4.]


In [12]:
import numpy as np

In [41]:
def solve_triangle(A, b, lower=True):
    """
    Решает СЛАУ с треугольной матрицей.
    A - матрица системы,
    b - правая часть системы,
    lower - если true, то матрица нижнетреугольная, иначе верхнетреугольная.
    """
    size = A.shape[0]
    indexes = range(size) if lower else reversed(range(size))
    
    x = np.zeros(size)
    for i in indexes:
        slice_indexes = slice(i) if lower else slice(size, i, -1)
        x[i] = (b[i] - A[i, slice_indexes] @ x[slice_indexes]) / A[i, i]
        
    return x

In [45]:
def lu(A, b):
    if np.linalg.det(A) == 0:
        raise Exception('Определитель матрицы равен 0')
    size = A.shape[0]
    L = np.zeros((size, size))
    U = np.copy(A)
    U = U.astype('float64')
    L = L.astype('float64')
    np.fill_diagonal(L, 1)
    for i in range(size):
        for j in range(i+1, size):
            L[j][i] = U[j][i] / U[i][i]
            U[j] = U[j] - L[j][i] * U[i]
    y = solve_triangle(L, b)    
    x = solve_triangle(U, y, lower=False)
    
    return L, U, x

In [46]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])
print(A)

[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]


In [47]:
lu(A, b)

(array([[1.        , 0.        , 0.        ],
        [5.5       , 1.        , 0.        ],
        [4.5       , 2.33333333, 1.        ]]),
 array([[  2.        ,   1.        ,   3.        ],
        [  0.        ,   1.5       , -11.5       ],
        [  0.        ,   0.        ,  17.33333333]]),
 array([-1.,  0.,  1.]))